/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.udesc.aula4.exerciciobanco;

import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class TelaCriarConta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCriarConta.class.getName());

    private Banco banco;
    /**
     * Creates new form TelaCriarConta
     */
    public TelaCriarConta(Banco banco) {
        this.banco = banco;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCriarConta = new javax.swing.JButton();
        cbContaPoupanca = new javax.swing.JCheckBox();
        lbNomeCorrentista = new javax.swing.JLabel();
        txtNomeCorrentista = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCriarConta.setText("Criar Conta");
        btnCriarConta.addActionListener(this::btnCriarContaActionPerformed);

        cbContaPoupanca.setText("Conta Poupança");

        lbNomeCorrentista.setText("Nome Correntista");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNomeCorrentista)
                    .addComponent(cbContaPoupanca, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(btnCriarConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbNomeCorrentista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbNomeCorrentista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeCorrentista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbContaPoupanca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCriarConta)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarContaActionPerformed
        String nomeCorrentista = txtNomeCorrentista.getText();
        Boolean isContaPoupanca = cbContaPoupanca.isSelected();
        
        if(validarDados()){
            ContaCorrente conta = criarConta(nomeCorrentista, isContaPoupanca);
            
            
            apresentarDados(getTipoConta(conta) + ": " + conta.getNomeCorrentista());            
        }
        else{
            apresentarDados("Preencha os dados corretamente");
        }

        limparTela();
    }//GEN-LAST:event_btnCriarContaActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public ContaCorrente criarConta(String nomeCorrentista, Boolean isContaPoupanca){
        if(isContaPoupanca)
            return banco.criarContaPoupanca(nomeCorrentista);
        else
            return banco.criarContaCorrente(nomeCorrentista);
    }
    
    public void apresentarDados(String mensagem){
        JOptionPane.showMessageDialog(null, mensagem);
    }
    
    public void limparTela(){
        txtNomeCorrentista.setText("");
        cbContaPoupanca.setSelected(false);
    }
    
    public Boolean validarDados(){
        if(txtNomeCorrentista.getText().equals(""))
            return false;
        else
            return true;
    }
    
    public String getTipoConta(ContaCorrente conta){
        if(conta instanceof ContaPoupanca)
            return "Conta Poupança";
        else
            return "Conta Corrente";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriarConta;
    private javax.swing.JCheckBox cbContaPoupanca;
    private javax.swing.JLabel lbNomeCorrentista;
    private javax.swing.JTextField txtNomeCorrentista;
    // End of variables declaration//GEN-END:variables
}
