/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.udesc.aula4.exerciciobanco;

import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class TelaCriarConta2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCriarConta2.class.getName());

    /**
     * Creates new form TelaCriarConta2
     */
    public TelaCriarConta2() {
        initComponents();
        initCbTipoContas();

    }
    
    public void initCbTipoContas(){
        cbTipoContas.addItem("Conta Corrente");
        cbTipoContas.addItem("Conta Poupança");
        cbTipoContas.addItem("Conta Salário");        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGroup = new javax.swing.ButtonGroup();
        radioContaCorrente = new javax.swing.JRadioButton();
        radioContaPoupanca = new javax.swing.JRadioButton();
        radioContaSalario = new javax.swing.JRadioButton();
        cbTipoContas = new javax.swing.JComboBox<>();
        bttCriarConta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        radioGroup.add(radioContaCorrente);
        radioContaCorrente.setText("Conta Corrente");

        radioGroup.add(radioContaPoupanca);
        radioContaPoupanca.setText("Conta Poupança");

        radioGroup.add(radioContaSalario);
        radioContaSalario.setText("Conta Salário");
        radioContaSalario.setToolTipText("");

        cbTipoContas.addActionListener(this::cbTipoContasActionPerformed);

        bttCriarConta.setText("Criar Conta");
        bttCriarConta.addActionListener(this::bttCriarContaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(radioContaPoupanca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioContaCorrente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioContaSalario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbTipoContas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttCriarConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(radioContaSalario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioContaCorrente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioContaPoupanca)
                .addGap(18, 18, 18)
                .addComponent(cbTipoContas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bttCriarConta)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttCriarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCriarContaActionPerformed
        if(radioContaCorrente.isSelected()){
            JOptionPane.showMessageDialog(null, "Conta Corrente");
        }else if(radioContaPoupanca.isSelected()){
            JOptionPane.showMessageDialog(null, "Conta Poupança");
        }else if(radioContaSalario.isSelected()){
            JOptionPane.showMessageDialog(null, "Conta Salário");
        }else
            JOptionPane.showMessageDialog(null, "Selecione uma das opções");
        
        String tipoSelecionado = (String) cbTipoContas.getSelectedItem();


    }//GEN-LAST:event_bttCriarContaActionPerformed

    private void cbTipoContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoContasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoContasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCriarConta2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttCriarConta;
    private javax.swing.JComboBox<String> cbTipoContas;
    private javax.swing.JRadioButton radioContaCorrente;
    private javax.swing.JRadioButton radioContaPoupanca;
    private javax.swing.JRadioButton radioContaSalario;
    private javax.swing.ButtonGroup radioGroup;
    // End of variables declaration//GEN-END:variables
}
